#######################################
# PROWLARR (DOWNLOAD INDEXING)
#######################################

services:
    prowlarr:
        container_name: prowlarr
        image: lscr.io/linuxserver/prowlarr:develop
        hostname: ${PROWLARR_SUBDOMAIN:-prowlarr}
        volumes:
            - ${MEDIA_CENTER_DIRECTORY}/prowlarr/config:/config
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: unless-stopped
        platform: ${DOCKER_PLATFORM:-linux/amd64}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.prowlarr-rtr.rule: Host(`${PROWLARR_SUBDOMAIN:-prowlarr}.${DOMAIN_NAME}`)
            traefik.http.routers.prowlarr-rtr.entrypoints: websecure
            traefik.http.routers.prowlarr-rtr.service: prowlarr-svc
            traefik.http.services.prowlarr-svc.loadbalancer.server.port: 9696
            traefik.http.routers.prowlarr-rtr.middlewares: chain-oauth-google@file
