#######################################
# SONARR (TV SHOW DOWNLOADS)
#######################################

services:
    sonarr:
        container_name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        profiles: ["media", "arrs", "all"]
        hostname: ${SONARR_SUBDOMAIN:-sonarr}
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/media/sonarr:/config
            - ${COMPLETED_DOWNLOADS}:/downloads
            - ${TV_DIR}:/tv
            - ${DOCKER_DIRECTORY}/stacks/media/shared:/shared
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        platform: ${DOCKER_PLATFORM:-linux/amd64}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.sonarr-rtr.rule: Host(`${SONARR_SUBDOMAIN:-sonarr}.${DOMAIN_NAME}`)
            traefik.http.routers.sonarr-rtr.entrypoints: websecure
            traefik.http.routers.sonarr-rtr.service: sonarr-svc
            traefik.http.services.sonarr-svc.loadbalancer.server.port: 8989
            traefik.http.routers.sonarr-rtr.middlewares: chain-oauth-google@file
