# yaml-language-server: $schema=https://schemastore.org/pre-commit-config.json

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
            exclude: mkdocs.yaml
          - id: check-ast
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: mixed-line-ending

    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.15.0
      hooks:
          - id: pretty-format-toml
            args: [--autofix, --no-sort]

    - repo: local
      hooks:
          - id: uv-lock
            name: uv-lock
            description: Runs uv lock when pyproject.toml changes
            entry: uv lock
            language: system
            pass_filenames: false
            files: pyproject.toml
          - id: prettier
            name: prettier
            description: Runs Prettier Code Formatter
            entry: prettier --write --ignore-unknown
            args: ["--tab-width=4"]
            language: node
            types:
                - text
            additional_dependencies:
                - prettier@3.6.2
