# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/refs/heads/main/schema/compose-spec.json

################################################################################
# HOMELAB
################################################################################

name: homelab

include:
    #############################################################################
    # MEDIA
    #############################################################################

    - apps/heimdall.yaml # Heimdall (Landing Page)
    - apps/plex.yaml # Plex (Media Server)
    - apps/sonarr.yaml # Sonarr (TV Show Downloads)
    - apps/radarr.yaml # Radarr (Movie Downloads)
    - apps/prowlarr.yaml # Prowlarr (Indexer)
    - apps/overseerr.yaml # Overseerr (Media Requests)
    - apps/tautulli.yaml # Tautulli (Plex Analytics)
    - apps/transmission.yaml # Transmission (Torrents Behind VPN)
    - apps/sabnzbd.yaml # SABnzbd (Usenet Downloading)
    - apps/nzbhydra.yaml # NZBHydra2 (Usenet Browsing)
    # - apps/readarr.yaml # Readarr (Ebook Downloads) [ARCHIVED]
    - apps/calibre.yaml # Calibre (Books Management)
    - apps/calibre-web.yaml # Calibre Web-UI

    #############################################################################
    # UTILITIES
    #############################################################################

    - apps/duckdns.yaml # DuckDNS (Dynamic DNS)
    # - apps/postgres.yaml # PostgreSQL (Shared Database)
    - apps/sftpgo.yaml # SFTPGo (File Management)
    - apps/pihole.yaml # Pi-hole (DNS Ad-Blocking)
    - apps/portainer.yaml # Portainer (Container Management)

    #############################################################################
    # MISCELLANEOUS
    #
    # * Note the existing services that are disabled by default.
    #############################################################################

    # - apps/libreoffice.yaml # LibreOffice (Office Suite)
    # - apps/umami.yaml # Umami Analytics
    - apps/homeassistant/docker-compose.yaml # Home Assistant (Smart Home)
    # - apps/healthchecks.yaml # Healthchecks (Monitoring)
    - apps/jellyfin.yaml
    - apps/camply/docker-compose.yaml
    - apps/coder.yaml # Coder (Remote Development)

    #############################################################################
    # LLM
    #
    # * Note the existing services that are disabled by default.
    #############################################################################
    - apps/open-webui.yaml # (LLM - OpenWebUI)
    - apps/chat-gpt-next-web.yaml # (LLM - NextChat)
    - apps/chatgpt-in-slack.yaml # ChatGPT Slack Bot
    - apps/litellm/docker-compose.yaml # (LLM - LiteLLM)

################################################################################
# NETWORK CONFIGURATION
################################################################################

networks:
    traefik:
        external: true
        name: homelab-core_traefik
    docker:
        external: true
        name: homelab-core_docker
    internal:
        external: true
        name: homelab-core_internal
