################################################################################
# HOMELAB
################################################################################

####################################
# INCLUDED STACKS
####################################

include:
    - stacks/traefik/docker-compose.yaml
    - stacks/media-center/docker-compose.yaml
    - stacks/miscellaneous/docker-compose.yaml

####################################
# CONFIGURATION
####################################

networks:
    traefik:
        driver: bridge
    docker:
        driver: bridge
    internal:
        driver: bridge
