################################################################################
# HOMELAB
################################################################################

include:
    #############################################################################
    # TRAEFIK (CORE)
    #############################################################################

    - stacks/core/traefik/docker-compose.yaml # Traefik (Reverse Proxy)
    - stacks/core/duckdns.yaml # DuckDNS (Dynamic DNS)
    - stacks/core/oauth.yaml # OAuth (Authentication)
    - stacks/core/socket-proxy.yaml # Docker Socket Proxy (Security)

    #############################################################################
    # MEDIA
    #############################################################################

    - stacks/media/heimdall.yaml # Heimdall (Landing Page)
    - stacks/media/plex.yaml # Plex (Media Server)
    - stacks/media/sonarr.yaml # Sonarr (TV Show Downloads)
    - stacks/media/radarr.yaml # Radarr (Movie Downloads)
    - stacks/media/prowlarr.yaml # Prowlarr (Indexer)
    - stacks/media/ombi.yaml # Ombi (Download Requests)
    - stacks/media/tautulli.yaml # Tautulli (Plex Analytics)
    - stacks/media/transmission.yaml # Transmission (Torrents Behind VPN)
    - stacks/media/sabnzbd.yaml # SABnzbd (Usenet Downloading)
    # - stacks/media/readarr.yaml # Readarr (Ebook Downloads)
    # - stacks/media/calibre.yaml # Calibre (Books Management)
    # - stacks/media/calibre-web.yaml # Calibre Web-UI

    #############################################################################
    # UTILITIES
    #############################################################################

    - stacks/utilities/watchtower.yaml #  Watchtower (Container Updating)
    # - stacks/utilities/postgres.yaml # PostgreSQL (Shared Database)
    # - stacks/utilities/sftpgo.yaml # SFTPGo (File Management)
    # - stacks/utilities/pihole.yaml # Pi-hole (DNS Ad-Blocking)
    # - stacks/utilities/portainer.yaml # Portainer (Container Management)

    #############################################################################
    # MISCELLANEOUS
    #
    # * Note the existing services that are disabled by default.
    #############################################################################

    # - stacks/miscellaneous/chat-gpt-next-web.yaml # ChatGPT Next Web
    # - stacks/miscellaneous/chatgpt-in-slack.yaml # ChatGPT Slack Bot
    # - stacks/miscellaneous/libreoffice.yaml # LibreOffice (Office Suite)

################################################################################
# NETWORK CONFIGURATION
################################################################################

networks:
    traefik:
        driver: bridge
    docker:
        driver: bridge
    internal:
        driver: bridge
