[project]
authors = [
  {name = "Justin Flannery", email = "juftin@juftin.com"}
]
description = "Homelab Deployment Via Docker-Compose"
license = "MIT"
name = "homelab"
readme = "README.md"
version = "0.5.1"
