services:
    ####################################
    # SOCKET-PROXY (DOCKER.SOCK)
    ####################################

    socket-proxy:
        container_name: socket-proxy
        image: tecnativa/docker-socket-proxy:latest
        profiles: ["traefik", "core", "all"]
        privileged: true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            docker:
        security_opt:
            - no-new-privileges:true
        restart: always
        platform: ${DOCKER_PLATFORM:-linux/amd64}
        environment:
            - LOG_LEVEL=info # debug, info, notice, warning, err, crit, alert, emerg
            - EVENTS=1
            - PING=1
            - VERSION=1
            - AUTH=0
            - SECRETS=0
            - POST=1
            - DELETE=1
            - BUILD=0
            - COMMIT=0
            - CONFIGS=0
            - CONTAINERS=1
            - DISTRIBUTION=0
            - EXEC=0
            - IMAGES=1
            - INFO=1
            - NETWORKS=1
            - NODES=0
            - PLUGINS=0
            - SERVICES=1
            - SESSION=0
            - SWARM=0
            - SYSTEM=0
            - TASKS=1
            - VOLUMES=1
