#######################################
# CALIBRE-WEB (CALIBRE WEB-UI)
#######################################

services:
    calibre-web:
        container_name: calibre-web
        image: lscr.io/linuxserver/calibre-web:latest
        hostname: ${CALIBRE_WEB_SUBDOMAIN:-calibre-web}
        volumes:
            - ${MEDIA_CENTER_DIRECTORY}/calibre-web/config:/config
            - ${BOOKS_DIR}:/books
            - ${MEDIA_CENTER_DIRECTORY}/calibre/config:/calibre-config
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            DOCKER_MODS: linuxserver/calibre-web:calibre
            OAUTHLIB_RELAX_TOKEN_SCOPE: 1
        security_opt:
            - no-new-privileges:true
        restart: unless-stopped
        platform: ${DOCKER_PLATFORM:-linux/amd64}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.calibre-web-rtr.rule: Host(`${CALIBRE_WEB_SUBDOMAIN:-calibre-web}.${DOMAIN_NAME}`)
            traefik.http.routers.calibre-web-rtr.entrypoints: https
            traefik.http.routers.calibre-web-rtr.service: calibre-web-svc
            traefik.http.services.calibre-web-svc.loadbalancer.server.port: 8083
            traefik.http.routers.calibre-web-rtr.middlewares: chain-oauth-google@file
