#######################################
# READARR (BOOKS AND AUDIOBOOKS)
#######################################

services:
    readarr:
        container_name: readarr
        image: lscr.io/linuxserver/readarr:develop
        hostname: ${READARR_SUBDOMAIN:-readarr}
        volumes:
            - ${DOCKER_DIRECTORY}/stacks/media-center/readarr/config:/config
            - ${COMPLETED_DOWNLOADS}:/downloads
            - ${BOOKS_DIR}:/books
            - ${DOCKER_DIRECTORY}/stacks/media-center/calibre/config:/calibre
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        platform: ${DOCKER_PLATFORM:-linux/amd64}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.readarr-rtr.rule: Host(`${READARR_SUBDOMAIN:-readarr}.${DOMAIN_NAME}`)
            traefik.http.routers.readarr-rtr.entrypoints: websecure
            traefik.http.routers.readarr-rtr.service: readarr-svc
            traefik.http.services.readarr-svc.loadbalancer.server.port: 8787
            traefik.http.routers.readarr-rtr.middlewares: chain-oauth-google@file
