version: '3.9'

################################################################################
# NETWORKING CONFIGURATION
################################################################################

networks:

    traefik:
        external: true
        name: traefik_traefik

################################################################################
# SERVICES CONFIGURATION
################################################################################

services:

    ####################################
    # HOSTED PI-HOLE DNS
    ####################################

    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        restart: ${UNIVERSAL_RESTART_POLICY}
        environment:
            TZ: ${TZ}
            WEBPASSWORD: ${ADMIN_PASSWORD}
            DNS1: 8.8.8.8
            DNS2: 8.8.4.4
            VIRTUAL_HOST: ${PIHOLE_SUBDOMAIN:-pihole}.${DOMAIN_NAME}
        volumes:
        -   ${MISCELLANEOUS_DIRECTORY}/pihole/etc-pihole/:/etc/pihole/
        -   ${MISCELLANEOUS_DIRECTORY}/config/etc-dnsmasq.d/:/etc/dnsmasq.d/
        networks:
            traefik:
        ports:
        -   ${PHYSICAL_SERVER_IP}:53:53/tcp
        -   ${PHYSICAL_SERVER_IP}:53:53/udp
        -   ${PHYSICAL_SERVER_IP}:67:67/udp
        cap_add:
        -   NET_ADMIN
        labels:
            traefik.enable: true
            traefik.http.routers.pihole-rtr.rule: Host(`${PIHOLE_SUBDOMAIN:-pihole}.${DOMAIN_NAME}`)
            traefik.http.routers.pihole-rtr.service: pihole-svc
            traefik.http.services.pihole-svc.loadbalancer.server.port: 80
            traefik.http.routers.pihole-rtr.entrypoints: https
            traefik.http.routers.pihole-rtr.middlewares: chain-oauth-google@file

    ####################################
    # ChatGPT Next Web
    ####################################

    chat-gpt-next-web:
        container_name: chat-gpt-next-web
        image: yidadaa/chatgpt-next-web:latest
        networks:
            traefik:
        environment:
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            TZ: ${TZ}
        labels:
            traefik.enable: true
            traefik.http.routers.chat-rtr.rule: Host(`${CHAT_SUBDOMAIN:-chat}.${DOMAIN_NAME}`)
            traefik.http.routers.chat-rtr.service: chat-svc
            traefik.http.services.chat-svc.loadbalancer.server.port: 3000
            traefik.http.routers.chat-rtr.entrypoints: https
            traefik.http.routers.chat-rtr.middlewares: chain-oauth-google@file

    ####################################
    # ChatGPT Slack Bot
    ####################################

    chatgpt-in-slack:
        container_name: chatgpt-in-slack
        image: juftin/chatgpt-in-slack:latest
        environment:
            SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
            SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            OPENAI_MODEL: ${OPENAI_MODEL:-gpt-3.5-turbo}
            TRANSLATE_MARKDOWN: ${TRANSLATE_MARKDOWN:-true}
            SLACK_APP_LOG_LEVEL: ${SLACK_APP_LOG_LEVEL:-DEBUG}
            TZ: ${TZ}
        restart: unless-stopped

    ####################################
    # Umami Analytics
    ####################################

    umami:
        image: ghcr.io/umami-software/umami:postgresql-latest
        ports:
        -   3000:3000
        environment:
            DATABASE_URL: postgresql://umami:umami@db:5432/umami
            DATABASE_TYPE: postgresql
            APP_SECRET: replace-me-with-a-random-string
        depends_on:
            db:
                condition: service_healthy
        restart: always
        healthcheck:
            test: [CMD-SHELL, "curl http://localhost:3000/api/heartbeat"]
            interval: 5s
            timeout: 5s
            retries: 5
        labels:
            traefik.enable: true
            traefik.http.routers.umami-rtr.rule: Host(`${UMAMI_SUBDOMAIN:-umami}.${DOMAIN_NAME}`)
            traefik.http.routers.umami-rtr.service: umami-svc
            traefik.http.services.umami-svc.loadbalancer.server.port: 3000
            traefik.http.routers.umami-rtr.entrypoints: https
            traefik.http.routers.umami-rtr.middlewares: chain-no-auth@file
    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: umami
            POSTGRES_USER: umami
            POSTGRES_PASSWORD: umami
        volumes:
        -   umami-db-data:/var/lib/postgresql/data
        restart: always
        healthcheck:
            test: [CMD-SHELL, 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
  umami-db-data:
