version: '3.9'

################################################################################
# NETWORKING CONFIGURATION
################################################################################

networks:

    traefik:
        external:
            name: traefik_traefik

################################################################################
# SERVICES CONFIGURATION
################################################################################

services:

    ####################################
    # HOSTED PI-HOLE DNS
    ####################################

    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        restart: ${UNIVERSAL_RESTART_POLICY}
        environment:
            TZ: ${TZ}
            WEBPASSWORD: ${ADMIN_PASSWORD}
            DNS1: 8.8.8.8
            DNS2: 8.8.4.4
            VIRTUAL_HOST: ${PIHOLE_SUBDOMAIN:-pihole}.${DOMAIN_NAME}
        volumes:
        -   ${MISCELLANEOUS_DIRECTORY}/pihole/etc-pihole/:/etc/pihole/
        -   ${MISCELLANEOUS_DIRECTORY}/config/etc-dnsmasq.d/:/etc/dnsmasq.d/
        networks:
            traefik:
        ports:
        -   ${PHYSICAL_SERVER_IP}:53:53/tcp
        -   ${PHYSICAL_SERVER_IP}:53:53/udp
        -   ${PHYSICAL_SERVER_IP}:67:67/udp
        cap_add:
        -   NET_ADMIN
        labels:
            traefik.enable: true
            traefik.http.routers.pihole-rtr.rule: Host(`${PIHOLE_SUBDOMAIN:-pihole}.${DOMAIN_NAME}`)
            traefik.http.routers.pihole-rtr.service: pihole-svc
            traefik.http.services.pihole-svc.loadbalancer.server.port: 80
            traefik.http.routers.pihole-rtr.entrypoints: https
            traefik.http.routers.pihole-rtr.middlewares: chain-oauth-google@file

    ####################################
    # HOSTED JUPYTER NOTEBOOK
    ####################################

    jupyter:
        container_name: jupyter
        image: juftin/jupyter:latest
        networks:
            traefik:
        restart: unless-stopped
        user: root
        environment:
            NB_USER: ${ADMIN_USER}
            NB_UID: ${PUID}
            NB_GID: ${PGID}
            JUPYTER_TOKEN: ${ADMIN_PASSWORD}
            PYTHONPATH: $${PYTHONPATH}:/home/${ADMIN_USER}/${SHARED_DIRECTORY_NAME}
        volumes:
        -   ${SHARED_DIRECTORY}:/home/${ADMIN_USER}/${SHARED_DIRECTORY_NAME}:rw
        labels:
            traefik.enable: true
            traefik.http.routers.jupyter-rtr.rule: Host(`${JUPYTER_SUBDOMAIN:-jupyter}.${DOMAIN_NAME}`)
            traefik.http.routers.jupyter-rtr.service: jupyter-svc
            traefik.http.services.jupyter-svc.loadbalancer.server.port: 8888
            traefik.http.routers.jupyter-rtr.entrypoints: https
            traefik.http.routers.jupyter-rtr.middlewares: chain-oauth-google@file
