http:
    middlewares:
        ####################################
        # CHAINS
        ####################################

        chain-rate-limit:
            chain:
                middlewares:
                    - middlewares-rate-limit

        chain-no-auth:
            chain:
                middlewares:
                    - middlewares-rate-limit
                    - middlewares-secure-headers

        chain-oauth-google:
            chain:
                middlewares:
                    - middlewares-rate-limit
                    - middlewares-secure-headers
                    - middlewares-oauth
