services:
    homeassistant:
        container_name: homeassistant
        image: homeassistant/home-assistant:2026.6.2@sha256:b82fab7973fa1ba5eb69a8aaab3a830d56d986d495d894faf0ee969ad27839a6
        volumes:
            - ${DOCKER_DIRECTORY}/apps/homeassistant/configuration.yaml:/config/configuration.yaml
            - ${DOCKER_DIRECTORY}/appdata/homeassistant:/config
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        security_opt:
            - no-new-privileges:true
        labels:
            traefik.enable: true
            traefik.http.routers.homeassistant-rtr.rule: Host(`${HOMEASSISTANT_SUBDOMAIN:-homeassistant}.${DOMAIN_NAME}`)
            traefik.http.routers.homeassistant-rtr.service: homeassistant-svc
            traefik.http.services.homeassistant-svc.loadbalancer.server.port: 8123
            traefik.http.routers.homeassistant-rtr.entrypoints: websecure
            traefik.http.routers.homeassistant-rtr.middlewares: chain-rate-limit@file
