services:
    homeassistant:
        container_name: homeassistant
        image: homeassistant/home-assistant:2026.4.4@sha256:c1e5f0147f4cb51ccb05bb30b62a1269cc1bd48a6274792d3b38a77ab274dfd2
        volumes:
            - ${DOCKER_DIRECTORY}/apps/homeassistant/configuration.yaml:/config/configuration.yaml
            - ${DOCKER_DIRECTORY}/appdata/homeassistant:/config
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        security_opt:
            - no-new-privileges:true
        labels:
            traefik.enable: true
            traefik.http.routers.homeassistant-rtr.rule: Host(`${HOMEASSISTANT_SUBDOMAIN:-homeassistant}.${DOMAIN_NAME}`)
            traefik.http.routers.homeassistant-rtr.service: homeassistant-svc
            traefik.http.services.homeassistant-svc.loadbalancer.server.port: 8123
            traefik.http.routers.homeassistant-rtr.entrypoints: websecure
            traefik.http.routers.homeassistant-rtr.middlewares: chain-rate-limit@file
