services:
    homeassistant:
        container_name: homeassistant
        image: homeassistant/home-assistant:2026.7.2@sha256:1476924357b46e80735c13e94232ba5c853cac052e9df4bb28d50fa56348097b
        volumes:
            - ${DOCKER_DIRECTORY}/apps/homeassistant/configuration.yaml:/config/configuration.yaml
            - ${DOCKER_DIRECTORY}/appdata/homeassistant:/config
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        security_opt:
            - no-new-privileges:true
        labels:
            traefik.enable: true
            traefik.http.routers.homeassistant-rtr.rule: Host(`${HOMEASSISTANT_SUBDOMAIN:-homeassistant}.${DOMAIN_NAME}`)
            traefik.http.routers.homeassistant-rtr.service: homeassistant-svc
            traefik.http.services.homeassistant-svc.loadbalancer.server.port: 8123
            traefik.http.routers.homeassistant-rtr.entrypoints: websecure
            traefik.http.routers.homeassistant-rtr.middlewares: chain-rate-limit@file
