http:

    middlewares:

        ####################################
        # MIDDLEWARES
        ####################################

        middlewares-rate-limit:
            rateLimit:
                average: 100
                burst:   50

        middlewares-secure-headers:
            headers:
                accessControlAllowMethods:
                    - GET
                    - OPTIONS
                    - PUT
                accessControlMaxAge:     100
                hostsProxyHeaders:
                    - "X-Forwarded-Host"
                sslRedirect:             true
                stsSeconds:              63072000
                stsIncludeSubdomains:    true
                stsPreload:              true
                forceSTSHeader:          true
                frameDeny:               false
                customFrameOptionsValue: "SAMEORIGIN"
                contentTypeNosniff:      true
                browserXssFilter:        true
                referrerPolicy:          "same-origin"
                featurePolicy:           "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
                customResponseHeaders:
                    X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
                    server:       ""

        middlewares-oauth:
            forwardAuth:
                address:            "http://oauth:4181"
                trustForwardHeader: true
                authResponseHeaders:
                    - "X-Forwarded-User"