# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# CALIBRE (BOOKS MANAGEMENT)
#######################################

services:
    calibre:
        container_name: calibre
        image: lscr.io/linuxserver/calibre:latest@sha256:c97f86a5acc3372d5e25e75b4c98d1bffa64e70d4c413554beb1e554ae109187
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/calibre:/config
            - ${BOOKS_DIR}:/books
            - ${COMPLETED_DOWNLOADS}:/downloads
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.calibre-rtr.rule: Host(`${CALIBRE_SUBDOMAIN:-calibre}.${DOMAIN_NAME}`)
            traefik.http.routers.calibre-rtr.entrypoints: websecure
            traefik.http.routers.calibre-rtr.service: calibre-svc
            traefik.http.services.calibre-svc.loadbalancer.server.port: 8080
            traefik.http.routers.calibre-rtr.middlewares: chain-oauth-google@file
