# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# CALIBRE (BOOKS MANAGEMENT)
#######################################

services:
    calibre:
        container_name: calibre
        image: lscr.io/linuxserver/calibre:latest@sha256:2e8a99a474d42d1ca13970d74ab83da5da93a1cf0c75e194ce696eceb3e20daa
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/calibre:/config
            - ${BOOKS_DIR}:/books
            - ${COMPLETED_DOWNLOADS}:/downloads
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.calibre-rtr.rule: Host(`${CALIBRE_SUBDOMAIN:-calibre}.${DOMAIN_NAME}`)
            traefik.http.routers.calibre-rtr.entrypoints: websecure
            traefik.http.routers.calibre-rtr.service: calibre-svc
            traefik.http.services.calibre-svc.loadbalancer.server.port: 8080
            traefik.http.routers.calibre-rtr.middlewares: chain-oauth-google@file
