# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# CALIBRE (BOOKS MANAGEMENT)
# Not working / not setup
#######################################

services:
    calibre:
        container_name: calibre
        image: lscr.io/linuxserver/calibre:latest
        profiles: [ "books", "all" ]
        volumes:
          - ${DOCKER_DIRECTORY}/appdata/calibre:/config
          - ${MEDIA_DIRECTORY}/data:/data
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
          - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.calibre-rtr.rule: Host(`${SUBDOMAIN__CALIBRE}.${DOMAIN_NAME}`)
            traefik.http.routers.calibre-rtr.entrypoints: websecure
            traefik.http.routers.calibre-rtr.service: calibre-svc
            traefik.http.services.calibre-svc.loadbalancer.server.port: 8080
            traefik.http.routers.calibre-rtr.middlewares: chain-oauth-google@file
