# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# ChatGPT Next Web
#######################################

services:
    chat-gpt-next-web:
        container_name: chat-gpt-next-web
        image: yidadaa/chatgpt-next-web:latest
        profiles: ["miscellaneous", "all"]
        networks:
            traefik:
        environment:
            DEFAULT_MODEL: ${DEFAULT_MODEL:-gpt-4o}
            OPENAI_API_KEY: ${OPENAI_API_KEY:-}
            ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
            ENABLE_BALANCE_QUERY: ${ENABLE_BALANCE_QUERY:-1}
            TZ: ${TZ}
        labels:
            traefik.enable: true
            traefik.http.routers.chat-rtr.rule: Host(`${CHAT_SUBDOMAIN:-chat}.${DOMAIN_NAME}`)
            traefik.http.routers.chat-rtr.service: chat-svc
            traefik.http.services.chat-svc.loadbalancer.server.port: 3000
            traefik.http.routers.chat-rtr.entrypoints: websecure
            traefik.http.routers.chat-rtr.middlewares: chain-oauth-google@file
