# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# ChatGPT Next Web
#######################################

services:
    chat-gpt-next-web:
        container_name: chat-gpt-next-web
        image: yidadaa/chatgpt-next-web:latest
        profiles: ["miscellaneous", "all"]
        networks:
            traefik:
        environment:
            TZ: ${TZ}
            OPENAI_API_KEY: ${OPENAI_API_KEY:-}
            ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
            CUSTOM_MODELS: -all,gpt-4o@OpenAI,gpt-4o-mini@OpenAI,claude-3-5-sonnet-20240620@Anthropic=claude-3-5-sonnet,claude-3-opus-20240229@Anthropic=claude-3-opus,claude-3-haiku-20240307@Anthropic=claude-3-haiku
            HIDE_USER_API_KEY: ${HIDE_USER_API_KEY:-1}
        labels:
            traefik.enable: true
            traefik.http.routers.chat-rtr.rule: Host(`${CHAT_SUBDOMAIN:-chat}.${DOMAIN_NAME}`)
            traefik.http.routers.chat-rtr.service: chat-svc
            traefik.http.services.chat-svc.loadbalancer.server.port: 3000
            traefik.http.routers.chat-rtr.entrypoints: websecure
            traefik.http.routers.chat-rtr.middlewares: chain-oauth-google@file
