# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# ChatGPT Next Web
#######################################

services:
    chat-gpt-next-web:
        container_name: chat-gpt-next-web
        image: yidadaa/chatgpt-next-web:v2.16.0
        profiles: ["llm", "all"]
        networks:
            traefik:
        environment:
            TZ: ${TZ}
            OPENAI_API_KEY: ${OPENAI_API_KEY:-}
            ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
            STABILITY_API_KEY: ${STABILITY_API_KEY:-}
            HIDE_USER_API_KEY: ${HIDE_USER_API_KEY:-1}
            DEFAULT_MODEL: +gpt-4.1@OpenAI
            CUSTOM_MODELS: >
                -all,
                gpt-4.1@OpenAI,
                chatgpt-4o-latest@OpenAI,
                gpt-4o@OpenAI,
                gpt-4o-mini@OpenAI,
                o1-pro@OpenAI,
                o3@OpenAI,
                o3-mini@OpenAI,
                o4-mini@OpenAI,
                gpt-4.1-mini@OpenAI,
                gpt-4.1-nano@OpenAI,
                claude-3-7-sonnet-latest@Anthropic,
                claude-3-5-haiku-latest@Anthropic,
                claude-3-opus-latest@Anthropic
        command:
            - sh
            - -c
            - export CUSTOM_MODELS=$(echo "$$CUSTOM_MODELS" | tr -d " ") && node server.js
        labels:
            traefik.enable: true
            traefik.http.routers.nextchat-rtr.rule: Host(`${NEXTCHAT_SUBDOMAIN:-nextchat}.${DOMAIN_NAME}`)
            traefik.http.routers.nextchat-rtr.service: nextchat-svc
            traefik.http.services.nextchat-svc.loadbalancer.server.port: 3000
            traefik.http.routers.nextchat-rtr.entrypoints: websecure
            traefik.http.routers.nextchat-rtr.middlewares: chain-oauth-google@file
