# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# DUCKDNS (DYNAMIC DNS MONITORING)
#######################################

services:
    duckdns:
        container_name: duckdns
        image: lscr.io/linuxserver/duckdns:latest@sha256:e73d36ae259e78f81f3ad7f54c712bd89f1330efa0a5904b9b67d93f502bbb70
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            SUBDOMAINS: ${DUCKDNS_SUBDOMAIN}
            TOKEN: ${DUCKDNS_TOKEN}
        networks:
            internal:
        security_opt:
            - no-new-privileges:true
        restart: always
