# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# DUCKDNS (DYNAMIC DNS MONITORING)
#######################################

services:
    duckdns:
        container_name: duckdns
        image: lscr.io/linuxserver/duckdns:latest@sha256:f8c485090831ba6ddbf4124ea3525977d39a838ec856e5327ccc01d884c3241c
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            SUBDOMAINS: ${DUCKDNS_SUBDOMAIN}
            TOKEN: ${DUCKDNS_TOKEN}
        networks:
            internal:
        security_opt:
            - no-new-privileges:true
        restart: always
