# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# DUCKDNS (DYNAMIC DNS MONITORING)
#######################################

services:
    duckdns:
        container_name: duckdns
        image: lscr.io/linuxserver/duckdns:latest@sha256:47582d7cc844d1675ea9cccea82cc28187d27e3ac9cfd757d21e0631ac0b268c
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            SUBDOMAINS: ${DUCKDNS_SUBDOMAIN}
            TOKEN: ${DUCKDNS_TOKEN}
        networks:
            internal:
        security_opt:
            - no-new-privileges:true
        restart: always
