services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
    - LOG_LEVEL=${LOG_LEVEL:-info}
    - LOG_HTML=${LOG_HTML:-false}
    - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    - TZ=${TZ}
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.overseerr-rtr.rule: Host(`${SUBDOMAIN__FLARESOLVERR}.${DOMAIN_NAME}`)
      traefik.http.routers.flaresolverr-rtr.entrypoints: websecure
      traefik.http.routers.flaresolverr-rtr.service: flaresolverr-svc
      traefik.http.services.flaresolverr-svc.loadbalancer.server.port: 8191
      traefik.http.routers.flaresolverr-rtr.middlewares: chain-oauth-google@file
