########################################################
# HEIMDALL HOMEPAGE
########################################################

services:
    heimdall:
        container_name: heimdall
        image: lscr.io/linuxserver/heimdall:latest
        profiles: ["media", "all"]
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/heimdall:/config
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.heimdall-rtr.rule: Host(`${DOMAIN_NAME}`) || Host(`www.${DOMAIN_NAME}`)
            traefik.http.routers.heimdall-rtr.entrypoints: websecure
            traefik.http.routers.heimdall-rtr.service: heimdall-svc
            traefik.http.services.heimdall-svc.loadbalancer.server.port: 80
            traefik.http.routers.heimdall-rtr.middlewares: chain-oauth-google@file
