services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    profiles: [ "utilities", "all" ]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${DOCKER_DIRECTORY}/appdata/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.http.routers.homepage-rtr.rule: Host(`${DOMAIN_NAME}`) || Host(`www.${DOMAIN_NAME}`) || Host(`${SUBDOMAIN__HOMEPAGE}.${DOMAIN_NAME}`)
      traefik.http.routers.homepage-rtr.entrypoints: websecure
      traefik.http.routers.homepage-rtr.service: homepage-svc
      traefik.http.services.homepage-svc.loadbalancer.server.port: 3000
      traefik.http.routers.homepage-rtr.middlewares: chain-oauth-google@file
