# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# HOSTED PI-HOLE DNS
#######################################

services:
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        profiles: ["utilities", "all"]
        environment:
            TZ: ${TZ}
            DNS1: 8.8.8.8
            DNS2: 8.8.4.4
            VIRTUAL_HOST: ${PIHOLE_SUBDOMAIN:-pihole}.${DOMAIN_NAME}
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/pihole/pihole/:/etc/pihole/
            - ${DOCKER_DIRECTORY}/appdata/pihole/dnsmasq.d/:/etc/dnsmasq.d/
        networks:
            traefik:
        ports:
            - ${PHYSICAL_SERVER_IP}:53:53/tcp
            - ${PHYSICAL_SERVER_IP}:53:53/udp
            - ${PHYSICAL_SERVER_IP}:67:67/udp
        cap_add:
            - NET_ADMIN
        labels:
            traefik.enable: true
            traefik.http.routers.pihole-rtr.rule: Host(`${PIHOLE_SUBDOMAIN:-pihole}.${DOMAIN_NAME}`)
            traefik.http.routers.pihole-rtr.service: pihole-svc
            traefik.http.services.pihole-svc.loadbalancer.server.port: 80
            traefik.http.routers.pihole-rtr.entrypoints: websecure
            traefik.http.routers.pihole-rtr.middlewares: chain-oauth-google@file
