#######################################
# PLEX (MOVIES AND TV SERVER)
#######################################

services:
    plex:
        container_name: plex
        image: lscr.io/linuxserver/plex:latest@sha256:a21302c5297943e204e9b262f8c2eca3e0c7ddb52490bfb3f1db47f6103721ab
        network_mode: host
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/plex:/config
            - ${TV_DIR}:/tv
            - ${MOVIE_DIR}:/movies
            - ${TRANSCODE_DIR:-/dev/shm}:/transcode
            - ${BOOKS_DIR}:/books
        devices:
            - /dev/dri:/dev/dri
            - /dev/dvb:/dev/dvb
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            VERSION: docker
            PLEX_CLAIM: ${PLEX_CLAIM}
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
