#######################################
# PLEX (MOVIES AND TV SERVER)
#######################################

services:
    plex:
        container_name: plex
        image: lscr.io/linuxserver/plex:latest@sha256:2785a6ad64d3a91529e31df678cf0f9fe8ddfe2718415222f270b8d1a6d765f0
        network_mode: host
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/plex:/config
            - ${TV_DIR}:/tv
            - ${MOVIE_DIR}:/movies
            - ${TRANSCODE_DIR:-/dev/shm}:/transcode
            - ${BOOKS_DIR}:/books
        devices:
            - /dev/dri:/dev/dri
            - /dev/dvb:/dev/dvb
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            VERSION: docker
            PLEX_CLAIM: ${PLEX_CLAIM}
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
