#######################################
# PLEX (MOVIES AND TV SERVER)
#######################################

services:
    plex:
        container_name: plex
        image: lscr.io/linuxserver/plex:latest@sha256:1720efa8e919a724ff3003cce7c1c0ae91a54e097ca3c8f6713a780c6fd73432
        network_mode: host
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/plex:/config
            - ${TV_DIR}:/tv
            - ${MOVIE_DIR}:/movies
            - ${TRANSCODE_DIR:-/dev/shm}:/transcode
            - ${BOOKS_DIR}:/books
        devices:
            - /dev/dri:/dev/dri
            - /dev/dvb:/dev/dvb
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
            VERSION: docker
            PLEX_CLAIM: ${PLEX_CLAIM}
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
