#######################################
# PROWLARR (DOWNLOAD INDEXING)
#######################################

services:
    prowlarr:
        container_name: prowlarr
        image: lscr.io/linuxserver/prowlarr:develop@sha256:85248c75ebf12f985bdd1d3b8f17deda23b7a5902aaa0888b9f13e57410580e9
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/prowlarr:/config
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.prowlarr-rtr.rule: Host(`${PROWLARR_SUBDOMAIN:-prowlarr}.${DOMAIN_NAME}`)
            traefik.http.routers.prowlarr-rtr.entrypoints: websecure
            traefik.http.routers.prowlarr-rtr.service: prowlarr-svc
            traefik.http.services.prowlarr-svc.loadbalancer.server.port: 9696
            traefik.http.routers.prowlarr-rtr.middlewares: chain-oauth-google@file
