#######################################
# RADARR (MOVIE DOWNLOADS)
#######################################

services:
    radarr:
        container_name: radarr
        image: lscr.io/linuxserver/radarr:latest@sha256:b01097ad2d948c9f5eca39eb60bb529e2e55b0738c4bf7db09383bef0abab59d
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/radarr:/config
            - ${COMPLETED_DOWNLOADS}:/downloads
            - ${MOVIE_DIR}:/movies
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.radarr-rtr.rule: Host(`${RADARR_SUBDOMAIN:-radarr}.${DOMAIN_NAME}`)
            traefik.http.routers.radarr-rtr.entrypoints: websecure
            traefik.http.routers.radarr-rtr.service: radarr-svc
            traefik.http.services.radarr-svc.loadbalancer.server.port: 7878
            traefik.http.routers.radarr-rtr.middlewares: chain-oauth-google@file
