# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# READARR (BOOKS AND AUDIOBOOKS)
#######################################

services:
    readarr:
        container_name: readarr
        image: lscr.io/linuxserver/readarr:develop
        profiles: ["media", "arrs", "all"]
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/readarr:/config
            - ${COMPLETED_DOWNLOADS}:/downloads
            - ${BOOKS_DIR}:/books
            - ${DOCKER_DIRECTORY}/appdata/calibre:/calibre
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.readarr-rtr.rule: Host(`${READARR_SUBDOMAIN:-readarr}.${DOMAIN_NAME}`)
            traefik.http.routers.readarr-rtr.entrypoints: websecure
            traefik.http.routers.readarr-rtr.service: readarr-svc
            traefik.http.services.readarr-svc.loadbalancer.server.port: 8787
            traefik.http.routers.readarr-rtr.middlewares: chain-oauth-google@file
