#######################################
# SABNZBD (USENET DOWNLOADING)
#######################################

services:
    sabnzbd:
        container_name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd:latest@sha256:e4573bab787c2ba9a9e6bbf5535da0bd9d4de8e247ac7fad6428319fadd2331d
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/sabnzbd:/config
            - ${COMPLETED_DOWNLOADS}:/downloads
            - ${INCOMPLETE_DOWNLOADS}:/incomplete-downloads
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.sabnzbd-rtr.rule: Host(`${SABNZBD_DOMAIN:-sabnzbd}.${DOMAIN_NAME}`)
            traefik.http.routers.sabnzbd-rtr.entrypoints: websecure
            traefik.http.routers.sabnzbd-rtr.service: sabnzbd-svc
            traefik.http.services.sabnzbd-svc.loadbalancer.server.port: 8080
            traefik.http.routers.sabnzbd-rtr.middlewares: chain-oauth-google@file
