# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# SOCKET-PROXY (DOCKER.SOCK)
#######################################

services:
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy:latest
    profiles:
      - traefik
      - core
      - all
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      docker: null
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      - LOG_LEVEL=notice
      - EVENTS=1
      - PING=1
      - VERSION=1
      - AUTH=0
      - SECRETS=0
      - POST=1
      - DELETE=1
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=0
      - PLUGINS=0
      - SERVICES=1
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1
      - VOLUMES=1
