# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#######################################
# TAUTULLI (PLEX SERVER MONITORING)
#######################################

services:
    tautulli:
        container_name: tautulli
        image: lscr.io/linuxserver/tautulli:latest@sha256:7077fd6654547c225ca5a740c4c954379129589f875c84cbe138641d4dd8a9d9
        volumes:
            - ${DOCKER_DIRECTORY}/appdata/tautulli:/config
            - ${DOCKER_DIRECTORY}/appdata/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        security_opt:
            - no-new-privileges:true
        restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
        networks:
            traefik:
        labels:
            traefik.enable: true
            traefik.http.routers.tautulli-rtr.rule: Host(`${TAUTULLI_SUBDOMAIN:-tautulli}.${DOMAIN_NAME}`)
            traefik.http.routers.tautulli-rtr.entrypoints: websecure
            traefik.http.routers.tautulli-rtr.service: tautulli-svc
            traefik.http.services.tautulli-svc.loadbalancer.server.port: 8181
            traefik.http.routers.tautulli-rtr.middlewares: chain-oauth-google@file
