####################################
# ChatGPT Next Web
####################################

services:
    chat-gpt-next-web:
        container_name: chat-gpt-next-web
        image: yidadaa/chatgpt-next-web:latest
        profiles: ["miscellaneous", "all"]
        networks:
            traefik:
        environment:
            OPENAI_API_KEY: ${OPENAI_API_KEY}
            TZ: ${TZ}
        platform: ${DOCKER_PLATFORM:-linux/amd64}
        labels:
            traefik.enable: true
            traefik.http.routers.chat-rtr.rule: Host(`${CHAT_SUBDOMAIN:-chat}.${DOMAIN_NAME}`)
            traefik.http.routers.chat-rtr.service: chat-svc
            traefik.http.services.chat-svc.loadbalancer.server.port: 3000
            traefik.http.routers.chat-rtr.entrypoints: websecure
            traefik.http.routers.chat-rtr.middlewares: chain-oauth-google@file
