name: Documentation

on:
    push:
        branches:
        -   main

jobs:
    github-pages-publish:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout Latest Changes
            uses: actions/checkout@v3
            with:
                ref: ${{ github.ref }}
                fetch-depth: 0
        -   name: Set up Python Environment
            uses: actions/setup-python@v2
            with:
                python-version: '3.9'
        -   name: Install Dependencies
            run: |
                pip install --upgrade pip wheel setuptools
                pip install mkdocs-material
        -   name: Deploy Documentation Changes
            run: mkdocs gh-deploy --force
