name: docs
on:
    push:
        branches: [main]
jobs:
    release:
        name: docs
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Set up Github Workspace
              uses: actions/checkout@v4
            - name: Setup Hatch
              uses: juftin/actions/hatch-setup@v1
              with:
                  python_version: "3.11"
            - name: Build Docs
              uses: juftin/actions/hatch-docs@v1
            - name: Publish Docs
              uses: juftin/actions/github-pages@v1
              id: deployment
