name: Release
on:
    push:
        branches: [main, next, beta, alpha, "*.x"]
jobs:
    release:
        name: Release
        if: github.repository_owner == 'juftin'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2
            - name: Semantic Release
              uses: juftin/actions/semantic-release@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
