# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: renovate
on:
    workflow_dispatch:
    schedule:
        - cron: "0/15 * * * *"
    push:
        paths:
            - .github/workflows/renovate.yaml
            - .github/renovate-config.js
            - .renovaterc.json5
        branches:
            - gitops
jobs:
    renovate:
        name: renovate
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}
            cancel-in-progress: false
        steps:
            - name: checkout
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
              with:
                  ref: gitops
            - name: renovate
              uses: renovatebot/github-action@8217b3fc286df088d7c27f3255fe8414463bc0fd # v46.1.15
              with:
                  token: ${{ secrets.RENOVATE_TOKEN }}
                  configurationFile: .github/renovate-config.js
                  renovate-version: 42.39.1
              env:
                  RENOVATE_REPOSITORY: ${{ github.repository }}
                  RENOVATE_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  RENOVATE_DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
                  LOG_LEVEL: info
