# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: test
on:
    pull_request:
        branches:
            - gitops
    merge_group:
        branches:
            - gitops
jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - name: docker-compose-validate
              run: |
                  cp docs/example.env .env
                  make validate
