# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: test
on:
    pull_request:
        branches:
            - gitops
    merge_group:
        branches:
            - gitops
jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: checkout
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
            - name: docker-compose-validate
              run: |
                  cp docs/example.env .env
                  make validate
